### ISSUE TITLE
coinbase is no show at :Modules -> Payment link, click on Coinbase Commerce

### ISSUE THREAD

**Issue by BMZ1322** [coinbase/coinbase-commerce-zencart#5]
I have copied files per README.MD from 'coinbase-commerce-zencart-master.zip' to proper folders but I do not see Coinbase Commerce in the admin,. In fact no other payment module shows after coinbase has been installed except those starting with 'a' , or 'b' such as Authorize.net.

What did I do wrong?

Thanks
Bahram

**Comment by oa-coinbase** [comment]
Hi there, unfortunately we are moving towards deprecating support for this plugin repository as it hasn't captured enough audience for us to maintain it at this time, although we may pick it up again in the future. The dependency [coinbase-commerce-php SDK](https://github.com/coinbase/coinbase-commerce-php) however will be kept alive. Feel free to clone this repository to make modifications for your use, or post any PR's you would like to fix for the php SDK to share with the community.

Alternatively, you may want to check out our [Shopify](https://commerce.coinbase.com/integrate/shopify) or [Woocommerce](https://commerce.coinbase.com/integrate/woocommerce) plugins.

Sorry we couldn't be more helpful at this time.
